apiVersion: apps/v1
kind: Deployment
metadata:
  name: rajarshi-app-deployment
spec: # Defines the deployment behavior
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: # Defines the POD behavior
      containers:
        - name: rishi-container
          image: muralisocial123/flower-app:1.0
          ports:
            - containerPort: 3015
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "250Mi"
              cpu: "100m"