apiVersion: apps/v1
kind: Deployment
metadata:
  name: rajarshi-app-deployment
spec: # Defines the deployment behavior
  replicas: 3
  selector:
    matchLabels:
      app: rishi1
  template:
    metadata:
      labels:
        app: rishi1
    spec: # Defines the POD behavior
      containers:
        - name: rishi-container
          image: muralisocial123/flower-app:1.0
          ports:
            - containerPort: 3015
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "250Mi"
              cpu: "100m"
---
# Writing the service.yaml file to expse the container
apiVersion: v1
kind: Service
metadata:
  name: rishi-app-svc
spec:
  selector:
    app: rishi1
  ports:
  - port: 3016
    targetPort: 3015
  type: LoadBalancer